apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: 'openkruise/helloworld-sample:v1'
          ports:
            - name: http-server
              containerPort: 9090
---
kind: Service
apiVersion: v1
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  ports:
    - port: 9090
      targetPort: http-server
  selector:
    app: helloworld
  type: LoadBalancer
