apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: {{ .Values.helloworld.fullname }}
  name: {{ .Values.installation.namespace }}
---
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  name: {{ .Values.helloworld.fullname }}
  labels:
    {{- toYaml .Values.helloworld.labels | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.helloworld.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.helloworld.labels | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
