apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.helloworld.fullname }}
  labels:
    {{- toYaml .Values.helloworld.labels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.helloworld.labels | nindent 4 }}
